packer {
  required_plugins {
    amazon = {
      version = ">=1.0.0"
      source = "github.com/hashicorp/amazon"
    }
  }
}                                                                                                  

source "amazon-ebs" "autogenerated_1" {                                                              
  ami_name      = "bharat-1"                                                                  
  instance_type = "t2.micro"                                                             
  region        = "us-west-2"                                                             
  source_ami    = "ami-b63ae0ce"                                                                     
  ssh_username  = "centos"                                                                         
}                                                                                                    

build {                                                                                              
  description = "AWS image"                                                                          
                                                                                                     
  sources = ["source.amazon-ebs.autogenerated_1"]                                                                                                                                                     
}